In [2]:
import array

In [3]:
ls=list(range(10))

In [4]:
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
var=array.array('i',ls) # in  indicate the integer here 

In [6]:
var

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# np.empty(5)

In [10]:
#value will be whatever if already exit in memory 
#It's show the memory allocation

### Data types of Numpy 
- boolen (true or false )
- int "$int32$ and $int64$" , ("int8" , use in indxing )
- float  "$float32$" and "$float64$"
- complex $complex64$ and the "$complex32$" comes under the float


In [11]:
# seed 

In [12]:
x=np.random.seed(10)

In [13]:
var1=np.random.randint(10,size=6)
var2=np.random.randint(10,size=(4,5))
var3=np.random.randint(10,size=(4,5,6))

In [14]:
print("the diminsion",var1.ndim) 
print("the shape of value",var2.shape)
print("the size is ",var3.size)
print("the dtype is ",var3.dtype)

the diminsion 1
the shape of value (4, 5)
the size is  120
the dtype is  int32


In [15]:
var1

array([9, 4, 0, 1, 9, 0])

In [16]:
#scrap the value from the array
var1[-1]

0

In [17]:
var2[0][0]

1

In [18]:
var2

array([[1, 8, 9, 0, 8],
       [6, 4, 3, 0, 4],
       [6, 8, 1, 8, 4],
       [1, 3, 6, 5, 3]])

In [19]:
#var2[3][0] # i am very happy 
#from second row strach 3,4 column
var2[3,0]

1

In [20]:
var2[1,3] #this is called indexing

0

In [21]:
#slicing here [start: stop: step]

In [22]:
var1[4:5]

array([9])

In [23]:
# indexing value [1,2,3,4,]
                  #[0,1,2,3]
#slicing [ value form A point to B point ]

In [24]:
var2

array([[1, 8, 9, 0, 8],
       [6, 4, 3, 0, 4],
       [6, 8, 1, 8, 4],
       [1, 3, 6, 5, 3]])

In [25]:
var2[2:3,2:4]

array([[1, 8]])

In [26]:
var2[:3,:2]

array([[1, 8],
       [6, 4],
       [6, 8]])

In [27]:
var2

array([[1, 8, 9, 0, 8],
       [6, 4, 3, 0, 4],
       [6, 8, 1, 8, 4],
       [1, 3, 6, 5, 3]])

In [28]:
var2[::-1,::-1]

array([[3, 5, 6, 3, 1],
       [4, 8, 1, 8, 6],
       [4, 0, 3, 4, 6],
       [8, 0, 9, 8, 1]])

In [29]:
#Reshaping the array

In [30]:
var4=np.arange(1,10).reshape(3,3)

##### example reshape
- you have called emp table here present only 1 row and you have 5 columns
- you have and another data department table they 2 rows and 10 columns 

In [31]:
var4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
var4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
var=np.array([1,2,3,4,5,6])
var

array([1, 2, 3, 4, 5, 6])

In [34]:
var.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [35]:
var.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [36]:
x=np.arange(1,5).reshape(2,2)

In [37]:
x

array([[1, 2],
       [3, 4]])

In [38]:
var5=np.arange(1,5)
var6=np.arange(6,10)

In [39]:
print(var5)
print(var6)

[1 2 3 4]
[6 7 8 9]


In [40]:
var7=np.concatenate([var5,var6])

In [41]:
var8=np.concatenate([var5,var6,var7])

In [42]:
var8

array([1, 2, 3, 4, 6, 7, 8, 9, 1, 2, 3, 4, 6, 7, 8, 9])

In [43]:
#split function in numpy
#same as the stering and we done list perivously

In [44]:
var9=np.arange(1,11)

In [45]:
var9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
var10=np.split(var9,[3])

In [47]:
var10

[array([1, 2, 3]), array([ 4,  5,  6,  7,  8,  9, 10])]

In [48]:
#now we split this in to more array
var11,var12,var13=np.split(var9,[3,5])

In [49]:
print(var13)

[ 6  7  8  9 10]


## Arthmatic  UFunction in NumPy
- np.add (+)
- np.substract (-)
- np.multiply (*)
- np.division (/)
- np.floor  (//)
- np.mod (%)
- np.power (**)
- np.squrt (**)

In [50]:
a1=np.array([11,99,55,42,-20,6,0,-13])

In [51]:
a1

array([ 11,  99,  55,  42, -20,   6,   0, -13])

In [52]:
a2=np.abs(a1) #absoulute function of numpy

In [53]:
a2

array([11, 99, 55, 42, 20,  6,  0, 13])

In [54]:
a3= np.arange(5)

In [55]:
print("value is : ",a3+55)
print("value is : ",a3-10)
print("value is : ",a3*12)
print("value is : ",a3/6)
print("value is : ",a3//6)
print("value is : ",a3**2)
print("value is : ",a3%6)

value is :  [55 56 57 58 59]
value is :  [-10  -9  -8  -7  -6]
value is :  [ 0 12 24 36 48]
value is :  [0.         0.16666667 0.33333333 0.5        0.66666667]
value is :  [0 0 0 0 0]
value is :  [ 0  1  4  9 16]
value is :  [0 1 2 3 4]


In [56]:
a4=np.arange(4).reshape(2,2)
a5=np.arange(4).reshape(2,2)

In [57]:
np.add(a4,a5)

array([[0, 2],
       [4, 6]])

In [58]:
np.average(a4)

1.5

### Trigonometric function
- sin thetha
 - cos
 - tan

In [108]:
#not more than value of 1
sin=np.sin(angle)
cosec=1/sin
cosec

array([1.18839511e+00, 1.13949393e+00, 8.16561968e+15])

In [ ]:
var= 

In [109]:
angle=np.linspace(0,np.pi,3) #most use ful function in data scientist using this

In [110]:
print("tan :",np.tan(angle))
print("sin :",1/np.sin(angle))
print("cos :",np.cos(angle))



tan : [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
sin : [           inf 1.00000000e+00 8.16561968e+15]
cos : [ 1.000000e+00  6.123234e-17 -1.000000e+00]


<ipython-input-110-c61c540b4fb8>:2: RuntimeWarning: divide by zero encountered in true_divide
  print("sin :",1/np.sin(angle))


In [63]:
value_of_ouput=[-1,0,1]

In [68]:
print("cos :",np.arccos(value_of_ouput))
print("sin :",np.arcsin(value_of_ouput))
print("tan :",np.arctan(value_of_ouput))



cos : [3.14159265 1.57079633 0.        ]
sin : [-1.57079633  0.          1.57079633]
tan : [-0.78539816  0.          0.78539816]


In [77]:
# In Numpy we have also a fucntion of np
np.log10(100)

2.0

In [78]:
log=[1,2,3]

In [88]:
log2=[1,2,4,6,8,10]

In [89]:
np.log(log2)

array([0.        , 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509])

In [90]:
np.log2(log2)

array([0.        , 1.        , 2.        , 2.5849625 , 3.        ,
       3.32192809])

In [91]:
np.log10(log2)

array([0.        , 0.30103   , 0.60205999, 0.77815125, 0.90308999,
       1.        ])

In [92]:
log3=[0,0.002,0.0045,0.1]

In [93]:
log3

[0, 0.002, 0.0045, 0.1]

In [99]:
np.exp(log3)

array([1.        , 1.002002  , 1.00451014, 1.10517092])

In [111]:
tri= np.array([np.pi/2])

In [112]:
tri

array([1.57079633])

In [115]:
x=np.sin(tri)

In [116]:
y=np.cos(tri)

In [117]:
tan=x/y

In [118]:
tan

array([1.63312394e+16])

In [119]:
np.tan(tri)

array([1.63312394e+16])

In [130]:
#aggreate functionag
ag= np.random.randint(10,size=(3,4))

In [154]:
ag

array([[7, 6, 9, 2],
       [0, 4, 5, 4],
       [6, 9, 0, 4]])

###  Numpy all the fun
- np.min(*arg)*
- np.max(*arg)*
- np.sum(*arg) **
- np.std(*arg) **
- np.var(*arg) **
- np.median(*arg) **
- np.any(*arg)
- np.all(*arg)
- np.percentile(*arg)
- np.mean(*arg) **

np.max(ag)

In [151]:
np.min(ag)

0

In [150]:
np.mean(ag)

4.666666666666667

In [149]:
np.std(ag) #standrand deviation

2.8674417556808756

In [145]:
np.median(ag)

4.5

In [148]:
np.var(ag)

8.222222222222223